//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDTARIF
    {
        public long SNO { get; set; }
        public string TARIFF_CODE { get; set; }
        public string COUNTRY { get; set; }
        public string PLANTYPE { get; set; }
        public string CURRENCY { get; set; }
        public string CHARGESTYPE { get; set; }
        public string VALUE { get; set; }
        public string TALK_VALUE { get; set; }
        public string PERMINCHARGES { get; set; }
        public string VALIDITY_DAYS { get; set; }
        public string COUNTRY_FROM { get; set; }
        public string COUNTRY_TO { get; set; }
        public string A { get; set; }
        public string B { get; set; }
        public string C { get; set; }
        public string D { get; set; }
    }
}
