//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Mvc3WithPartialview_14Sep2014.EF
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class abhiEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new abhiEntities object using the connection string found in the 'abhiEntities' section of the application configuration file.
        /// </summary>
        public abhiEntities() : base("name=abhiEntities", "abhiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new abhiEntities object.
        /// </summary>
        public abhiEntities(string connectionString) : base(connectionString, "abhiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new abhiEntities object.
        /// </summary>
        public abhiEntities(EntityConnection connection) : base(connection, "abhiEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employee> Employees
        {
            get
            {
                if ((_Employees == null))
                {
                    _Employees = base.CreateObjectSet<Employee>("Employees");
                }
                return _Employees;
            }
        }
        private ObjectSet<Employee> _Employees;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employees EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployees(Employee employee)
        {
            base.AddObject("Employees", employee);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="abhiModel", Name="Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="empId">Initial value of the EmpId property.</param>
        /// <param name="empSalary">Initial value of the EmpSalary property.</param>
        public static Employee CreateEmployee(global::System.Int32 empId, global::System.Decimal empSalary)
        {
            Employee employee = new Employee();
            employee.EmpId = empId;
            employee.EmpSalary = empSalary;
            return employee;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 EmpId
        {
            get
            {
                return _EmpId;
            }
            set
            {
                if (_EmpId != value)
                {
                    OnEmpIdChanging(value);
                    ReportPropertyChanging("EmpId");
                    _EmpId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EmpId");
                    OnEmpIdChanged();
                }
            }
        }
        private global::System.Int32 _EmpId;
        partial void OnEmpIdChanging(global::System.Int32 value);
        partial void OnEmpIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmpName
        {
            get
            {
                return _EmpName;
            }
            set
            {
                OnEmpNameChanging(value);
                ReportPropertyChanging("EmpName");
                _EmpName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmpName");
                OnEmpNameChanged();
            }
        }
        private global::System.String _EmpName;
        partial void OnEmpNameChanging(global::System.String value);
        partial void OnEmpNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal EmpSalary
        {
            get
            {
                return _EmpSalary;
            }
            set
            {
                OnEmpSalaryChanging(value);
                ReportPropertyChanging("EmpSalary");
                _EmpSalary = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EmpSalary");
                OnEmpSalaryChanged();
            }
        }
        private global::System.Decimal _EmpSalary;
        partial void OnEmpSalaryChanging(global::System.Decimal value);
        partial void OnEmpSalaryChanged();

        #endregion

    
    }

    #endregion

    
}
