//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication22
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
  
    public partial class mvc5Entities2 : DbContext
    {
        public mvc5Entities2()
            : base("name=mvc5Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<angcontr> angcontrs { get; set; }
    }
}
